_format_version: "3.0"
services:
- name: argocd-service
  enabled: true
  host: argocd-server.stage-argocd.svc.cluster.local
  path: /
  port: 80
  protocol: http
  connect_timeout: 60000
  read_timeout: 60000
  write_timeout: 60000
  retries: 5
  routes:
  - name: argocd-route
    https_redirect_status_code: 426
    path_handling: v0
    paths:
    - /argocd
    preserve_host: true
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: false
    response_buffering: false
    strip_path: true