_format_version: "3.0"
services:
- name: argocd-server
  enabled: true
  host: localhost #argocd-server.stage-argocd.svc.cluster.local
  path: /
  port: 80
  protocol: http
  connect_timeout: 60000
  read_timeout: 60000
  write_timeout: 60000
  retries: 5
  routes:
  - name: argocd-route
    https_redirect_status_code: 426
    path_handling: v0
    paths:
    - /argocd
    preserve_host: true
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: false
    response_buffering: false
    strip_path: true

- name: stage-fe-hostmain-svc
  enabled: true
  host: stage-fe-hostmain-svc.stage-fe-hostmain.svc.cluster.local #10.2.23.121 #argocd-server.stage-argocd.svc.cluster.local
  path: /
  port: 80
  protocol: http
  connect_timeout: 60000 
  read_timeout: 60000
  write_timeout: 60000
  retries: 5
  routes:
   - name: stage-host-route
     https_redirect_status_code: 426
     path_handling: v0
     hosts:
      - stage-host.bibian.co.jp
     paths:
     - /
     preserve_host: true
     protocols:
     - http
     - https
     regex_priority: 0
     request_buffering: false
     response_buffering: false
     strip_path: false