apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: kong-config # 對應到 kong-values.yaml 的 configMap name生成的 ConfigMap 名稱
  files:
  - kong.yml
generatorOptions:
 disableNameSuffixHash: true