apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: stage-kong
data:
  kong.yaml: |-
    _format_version: "3.0"
    services:
    - name: argocd-service
      url: http://argocd-server.argocd.svc.cluster.local:80  # Argo CD 內部 HTTPS
      routes:
      - name: argocd-route
        paths:
        - /argocd
        strip_path: true
        protocols: ["http", "https"]  # 支持 HTTP 和 HTTPS