image:
  repository: kong:latest
  tag: latest

namespace: stage-kong

kong:
  database: "off"
  declarativeConfig: "/kong/kong.yaml"
  proxyListen: "0.0.0.0:8000, 0.0.0.0:8443 ssl"

replicas: 3

service:
  type: LoadBalancer

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    path: /status
    port: 8001
    scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /status
    port: 8001
    scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10