apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: {{ .Values.image.repository }}
        env:
        - name: KONG_DATABASE
          value: {{ .Values.kong.database | quote }}
        - name: KONG_DECLARATIVE_CONFIG
          value: {{ .Values.kong.declarativeConfig | quote }}
        - name: KONG_PROXY_LISTEN
          value: {{ .Values.kong.proxyListen | quote }}
        resources:
          {{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          {{ toYaml .Values.probes.liveness | indent 10 }}
        readinessProbe:
          {{ toYaml .Values.probes.readiness | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /kong
        - name: tls
          mountPath: /etc/kong/tls
        ports:
        - containerPort: 8000
        - containerPort: 8443
      volumes:
      - name: config
        configMap:
          name: kong-config
      - name: tls
        secret:
          secretName: kong-tls